apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.url }}  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app
                port:
                  number: 80
