name: Docker Image Build & Push To Registery

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ secrets.DOCKER_REGISTRY }}

      - name: Set image tag
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/heads/}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/coworking-space-api:${{ steps.tag.outputs.TAG }} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/coworking-space-api:${{ steps.tag.outputs.TAG }}
