name: Release Helm Chart

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.2.4'

      - name: Package Helm chart
        run: |
          helm package ./charts -d ./charts_dist
          helm repo index ./charts_dist --url https://github.com/aazmy/the-coworking-space-app/releases/latest

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          draft: false
          prerelease: false

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v2
        with:
          name: helm-charts
          path: ./charts_dist

      - name: Release created
        run: echo "Release created at ${{ steps.create_release.outputs.upload_url }}"
